/* Database schema to keep the structure of entire database. */


CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name varchar(255),
    age int,
    PRIMARY KEY(id)
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    PRIMARY KEY(id)
);

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id),
    owner_id INT REFERENCES owners(id),
    species_id INT REFERENCES species(id)
);